version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.8.0-browsers
    steps:
      - checkout
      - run: echo "Running example step, please edit this file"

workflows:
  test-flow:
    jobs:
      - test
[![Upload Python Package](https://github.com/lucidrains/phenaki-pytorch/actions/workflows/python-publish.yml/badge.svg?branch=main&event=check_run)](https://github.com/lucidrains/phenaki-pytorch/actions/workflows/python-publish.yml)